apply plugin: 'com.android.library'

android {
    namespace "com.termux.emulator"
    compileSdk project.properties.compileSdkVersion.toInteger()
    defaultConfig { minSdk project.properties.minSdkVersion.toInteger() }
    buildTypes { release { minifyEnabled false; proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' } }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
dependencies { implementation "androidx.annotation:annotation:1.9.0"; testImplementation "junit:junit:4.13.2" }
