apply plugin: 'com.android.library'
android { namespace "com.termux.view"; compileSdk project.properties.compileSdkVersion.toInteger(); defaultConfig { minSdk project.properties.minSdkVersion.toInteger() }; buildTypes { release { minifyEnabled false } }; compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 } }
dependencies { implementation "androidx.annotation:annotation:1.9.0"; api project(":terminal-emulator"); testImplementation "junit:junit:4.13.2" }
